In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

This EDA is performed on the four datasets I collected in csv format:
- `raw_bike_sharing_systems.csv`:  A list of active bike-sharing systems across the world
- `cities_weather_forecast.csv`: 5-day weather forecasts for a list of cities, from OpenWeather API
- `raw_worldcities.csv`: A list of major cities' info (such as name, latitude and longitude) across the world
- `raw_seoul_bike_sharing.csv`: Weather information (Temperature, Humidity, Windspeed, Visibility, Dewpoint, Solar radiation, Snowfall, Rainfall), the number of bikes rented per hour, and date information, from Seoul bike-sharing systems

In [2]:
dataset_list <- c('../data_raw/raw_bike_sharing_systems.csv', '../data_raw/raw_seoul_bike_sharing.csv', '../data_raw/cities_weather_forecast.csv', '../data_raw/raw_worldcities.csv')

Let's take a look at the raw datasets

In [3]:
for (dataset_name in dataset_list){
    # Print a summary for each data set to check whether the column names are in proper standard naming convention
    dataset <- read_csv(dataset_name)
    print(head(dataset), width = Inf)
}

Rows: 480 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (10): COUNTRY, City, Name, SYSTEM, OPERATOR, LAUNCHED, DISCONTINUED, STA...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# A tibble: 6 × 10
  COUNTRY   City                  Name                 SYSTEM
  <chr>     <chr>                 <chr>                <chr>
1 Albania   Tirana                Ecovolis             NA
2 Argentina Mendoza               Metrobici            NA
3 Argentina San Lorenzo, Santa Fe Biciudad             Biciudad
4 Argentina Buenos Aires          Ecobici              Serttel Brasil
5 Argentina Rosario               Mi Bici Tu Bici[11]  NA
6 Australia Melbourne[12]         Melbourne Bike Share PBSC & 8D
  OPERATOR                       LAUNCHED         DISCONTINUED         STATIONS
  <chr>                          <chr>            <chr>                <chr>
1 NA                             March 2011       NA                   8
2 NA                             2014             NA                   2
3 NA                             27 November 2016 NA                   8
4 Bike In Baires Consortium.[10] 2010             NA                   400
5 NA                             2 December 2015  NA                   47
6 Motivate                       June 2010        30 November 2019[13] 53
  BICYCLES DAILY_RIDERSHIP
  <chr>    <chr>
1 200      NA
2 40       NA
3 80       NA
4 4000     21917
5 480      NA
6 676      NA

Rows: 8760 Columns: 14
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): Date, SEASONS, HOLIDAY, FUNCTIONING_DAY
dbl (10): RENTED_BIKE_COUNT, Hour, TEMPERATURE, HUMIDITY, WIND_SPEED, Visibi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# A tibble: 6 × 14
  Date       RENTED_BIKE_COUNT  Hour TEMPERATURE HUMIDITY WIND_SPEED Visibility
  <chr>                  <dbl> <dbl>       <dbl>    <dbl>      <dbl>      <dbl>
1 01/12/2017               254     0        -5.2       37        2.2       2000
2 01/12/2017               204     1        -5.5       38        0.8       2000
3 01/12/2017               173     2        -6         39        1         2000
4 01/12/2017               107     3        -6.2       40        0.9       2000
5 01/12/2017                78     4        -6         36        2.3       2000
6 01/12/2017               100     5        -6.4       37        1.5       2000
  DEW_POINT_TEMPERATURE SOLAR_RADIATION RAINFALL Snowfall SEASONS HOLIDAY
                  <dbl>           <dbl>    <dbl>    <dbl> <chr>   <chr>
1                 -17.6               0        0        0 Winter  No Holiday
2                 -17.6               0        0        0 Winter  No Holiday
3                 -17.7               0        0        0 Winter  No Holiday
4                 -17.6               0        0        0 Winter  No Holiday
5                 -18.6               0        0        0 Winter  No Holiday
6                 -18.7               0        0        0 Winter  No Holiday
  FUNCTIONING_DAY
  <chr>
1 Yes
2 Yes
3 Yes
4 Yes
5 Yes
6 Yes

New names:
• `` -> `...1`
Rows: 0 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): ...1

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# A tibble: 0 × 1
# ℹ 1 variable: ...1 <chr>

Rows: 26569 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (7): City, CITY_ASCII, COUNTRY, ISO2, ISO3, ADMIN_NAME, CAPITAL
dbl (4): LAT, LNG, POPULATION, ID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# A tibble: 6 × 11
  City     CITY_ASCII   LAT   LNG COUNTRY     ISO2  ISO3  ADMIN_NAME  CAPITAL
  <chr>    <chr>      <dbl> <dbl> <chr>       <chr> <chr> <chr>       <chr>
1 Tokyo    Tokyo      35.7  140.  Japan       JP    JPN   Tōkyō       primary
2 Jakarta  Jakarta    -6.21 107.  Indonesia   ID    IDN   Jakarta     primary
3 Delhi    Delhi      28.7   77.2 India       IN    IND   Delhi       admin
4 Mumbai   Mumbai     19.0   72.8 India       IN    IND   Mahārāshtra admin
5 Manila   Manila     14.6  121.  Philippines PH    PHL   Manila      primary
6 Shanghai Shanghai   31.2  121.  China       CN    CHN   Shanghai    admin
  POPULATION         ID
       <dbl>      <dbl>
1   37977000 1392685764
2   34540000 1360771077
3   29617000 1356872604
4   23355000 1356226629
5   23088000 1608618140
6   22120000 1156073548

Read the datasets and check whether their column names follow the standard naming convention

In [4]:
for (dataset_name in dataset_list){
    # Print a summary for each data set to check whether the column names are in proper standard naming convention
    dataset <- read_csv(dataset_name)
    print(summary(dataset))
}

Rows: 480 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (10): COUNTRY, City, Name, SYSTEM, OPERATOR, LAUNCHED, DISCONTINUED, STA...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

   COUNTRY              City               Name              SYSTEM
 Length:480         Length:480         Length:480         Length:480
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character
   OPERATOR           LAUNCHED         DISCONTINUED         STATIONS
 Length:480         Length:480         Length:480         Length:480
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character
   BICYCLES         DAILY_RIDERSHIP
 Length:480         Length:480
 Class :character   Class :character
 Mode  :character   Mode  :character

Rows: 8760 Columns: 14
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): Date, SEASONS, HOLIDAY, FUNCTIONING_DAY
dbl (10): RENTED_BIKE_COUNT, Hour, TEMPERATURE, HUMIDITY, WIND_SPEED, Visibi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

     Date           RENTED_BIKE_COUNT      Hour        TEMPERATURE
 Length:8760        Min.   :   2.0    Min.   : 0.00   Min.   :-17.80
 Class :character   1st Qu.: 214.0    1st Qu.: 5.75   1st Qu.:  3.40
 Mode  :character   Median : 542.0    Median :11.50   Median : 13.70
                    Mean   : 729.2    Mean   :11.50   Mean   : 12.87
                    3rd Qu.:1084.0    3rd Qu.:17.25   3rd Qu.: 22.50
                    Max.   :3556.0    Max.   :23.00   Max.   : 39.40
                    NA's   :295                       NA's   :11
    HUMIDITY       WIND_SPEED      Visibility   DEW_POINT_TEMPERATURE
 Min.   : 0.00   Min.   :0.000   Min.   :  27   Min.   :-30.600
 1st Qu.:42.00   1st Qu.:0.900   1st Qu.: 940   1st Qu.: -4.700
 Median :57.00   Median :1.500   Median :1698   Median :  5.100
 Mean   :58.23   Mean   :1.725   Mean   :1437   Mean   :  4.074
 3rd Qu.:74.00   3rd Qu.:2.300   3rd Qu.:2000   3rd Qu.: 14.800
 Max.   :98.00   Max.   :7.400   Max.   :2000   Max.   : 27.200

 SOLAR_RADIATION     RAINFALL          Snowfall         SEASONS
 Min.   :0.0000   Min.   : 0.0000   Min.   :0.00000   Length:8760
 1st Qu.:0.0000   1st Qu.: 0.0000   1st Qu.:0.00000   Class :character
 Median :0.0100   Median : 0.0000   Median :0.00000   Mode  :character
 Mean   :0.5691   Mean   : 0.1487   Mean   :0.07507
 3rd Qu.:0.9300   3rd Qu.: 0.0000   3rd Qu.:0.00000
 Max.   :3.5200   Max.   :35.0000   Max.   :8.80000

   HOLIDAY          FUNCTIONING_DAY
 Length:8760        Length:8760
 Class :character   Class :character
 Mode  :character   Mode  :character

New names:
• `` -> `...1`
Rows: 0 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): ...1

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

     ...1
 Length:0
 Class :character
 Mode  :character

Rows: 26569 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (7): City, CITY_ASCII, COUNTRY, ISO2, ISO3, ADMIN_NAME, CAPITAL
dbl (4): LAT, LNG, POPULATION, ID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

     City            CITY_ASCII             LAT              LNG
 Length:26569       Length:26569       Min.   :-54.93   Min.   :-179.5900
 Class :character   Class :character   1st Qu.: 27.92   1st Qu.: -78.7794
 Mode  :character   Mode  :character   Median : 40.22   Median :  -0.7689
                                       Mean   : 33.10   Mean   : -11.3639
                                       3rd Qu.: 47.99   3rd Qu.:  29.6833
                                       Max.   : 81.72   Max.   : 179.3667

   COUNTRY              ISO2               ISO3            ADMIN_NAME
 Length:26569       Length:26569       Length:26569       Length:26569
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




   CAPITAL            POPULATION             ID
 Length:26569       Min.   :       0   Min.   :1.004e+09
 Class :character   1st Qu.:    9246   1st Qu.:1.277e+09
 Mode  :character   Median :   20080   Median :1.643e+09
                    Mean   :  162346   Mean   :1.556e+09
                    3rd Qu.:   59369   3rd Qu.:1.840e+09
                    Max.   :37977000   Max.   :1.934e+09
                    NA's   :973

Upon first glance, it appears that the column names are not standardized. 
Another major issue is that there is a duplicate column for `COUNTRY` in the `raw_bike_sharing_systems.csv` dataset.

Check the types of the selected columns for any inconsistencies

In [5]:
for(dataset_name in dataset_list){
    dataset <- read_csv(dataset_name)
    print(
        dataset %>% summarise(across(everything(), class)) %>%
      pivot_longer(cols = everything(), names_to = "variable", values_to = "class")
    )
}

Rows: 480 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (10): COUNTRY, City, Name, SYSTEM, OPERATOR, LAUNCHED, DISCONTINUED, STA...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# A tibble: 10 × 2
   variable        class
   <chr>           <chr>
 1 COUNTRY         character
 2 City            character
 3 Name            character
 4 SYSTEM          character
 5 OPERATOR        character
 6 LAUNCHED        character
 7 DISCONTINUED    character
 8 STATIONS        character
 9 BICYCLES        character
10 DAILY_RIDERSHIP character

Rows: 8760 Columns: 14
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): Date, SEASONS, HOLIDAY, FUNCTIONING_DAY
dbl (10): RENTED_BIKE_COUNT, Hour, TEMPERATURE, HUMIDITY, WIND_SPEED, Visibi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# A tibble: 14 × 2
   variable              class
   <chr>                 <chr>
 1 Date                  character
 2 RENTED_BIKE_COUNT     numeric
 3 Hour                  numeric
 4 TEMPERATURE           numeric
 5 HUMIDITY              numeric
 6 WIND_SPEED            numeric
 7 Visibility            numeric
 8 DEW_POINT_TEMPERATURE numeric
 9 SOLAR_RADIATION       numeric
10 RAINFALL              numeric
11 Snowfall              numeric
12 SEASONS               character
13 HOLIDAY               character
14 FUNCTIONING_DAY       character

New names:
• `` -> `...1`
Rows: 0 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): ...1

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# A tibble: 1 × 2
  variable class
  <chr>    <chr>
1 ...1     character

Rows: 26569 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (7): City, CITY_ASCII, COUNTRY, ISO2, ISO3, ADMIN_NAME, CAPITAL
dbl (4): LAT, LNG, POPULATION, ID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# A tibble: 11 × 2
   variable   class
   <chr>      <chr>
 1 City       character
 2 CITY_ASCII character
 3 LAT        numeric
 4 LNG        numeric
 5 COUNTRY    character
 6 ISO2       character
 7 ISO3       character
 8 ADMIN_NAME character
 9 CAPITAL    character
10 POPULATION numeric
11 ID         numeric

They are all interpreted as character columns, but I expect the `BICYCLES` and `DAILY_RIDERSHIP` column to be of numeric type. Let's see why it wasn't loaded as a numeric column - possibly some entries contain characters.

In [6]:
# grepl searches a string for non-digital characters, and returns TRUE or FALSE
# if it finds any non-digital characters, then a column is not purely numeric
find_character <- function(strings) grepl("[^0-9]", strings)

In [7]:
dataset <- read_csv('../data_raw/raw_bike_sharing_systems.csv')
dataset %>% 
    select(BICYCLES) %>% 
    filter(find_character(BICYCLES)) %>%
    slice(0:10)

Rows: 480 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (10): COUNTRY, City, Name, SYSTEM, OPERATOR, LAUNCHED, DISCONTINUED, STA...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

   BICYCLES
1  4115[22]
2  310[59]
3  500[72]
4  [75]
5  180[76]
6  600[77]
7  [78]
8  initially 800 (later 2500)
9  100 (220)
10 370[114]

As can be seen, many rows have non-numeric characters, such as `32 (including 6 rollers) [162]` and `1000[253]`. This is actually very common for a table scraped from Wiki when no input validation is enforced.

Next, I take a look at the other columns, namely `COUNTRY`, `CITY`, and `SYSTEM`, to see if they contain any undesired reference links, such as `Melbourne[12]` for example.

In [8]:
# Defined a 'reference link' character class, 
# `[A-z0-9]` means at least one character 
# `\\[` and `\\]` means the character is wrapped by [], such as for [12] or [abc]
ref_pattern <- "\\[[A-z0-9]+\\]"
find_reference_pattern <- function(strings) grepl(ref_pattern, strings)

In [9]:
# Check whether the COUNTRY column has any reference links
dataset %>% 
    select(COUNTRY) %>% 
    filter(find_reference_pattern(COUNTRY)) %>%
    slice(0:10)

     COUNTRY

Ok, looks like the `COUNTRY` column is clean. Let's check the `CITY` column.

In [10]:
# Check whether the CITY column has any reference links
dataset %>% 
    select(City) %>% 
    filter(find_reference_pattern(City)) %>%
    slice(0:10)

   City
1  Melbourne[12]
2  Brisbane[14][15]
3  Lower Austria[18]
4  Namur[19]
5  Brussels[21]
6  Salvador[23]
7  Belo Horizonte[24]
8  João Pessoa[25]
9  (Pedro de) Toledo[26]
10 Rio de Janeiro[27]

Looks like the `CITY` column has some reference links to be removed. Next, let's check the `SYSTEM` column.

In [11]:
# Check whether the System column has any reference links
dataset %>% 
    select(SYSTEM) %>% 
    filter(find_reference_pattern(SYSTEM)) %>%
    slice(0:10)

  SYSTEM
1 EasyBike[58]
2 4 Gen.[61]
3 3 Gen. SmooveKey[113]
4 3 Gen. Smoove[141][142][143][139]
5 3 Gen. Smoove[179]
6 3 Gen. Smoove[181]
7 3 Gen. Smoove[183]

So the `SYSTEM` column also has some reference links.

After some preliminary investigations, we identified that the `CITY` and `SYSTEM` columns have some undesired reference links, and the `BICYCLES` column has both reference links and some textual annotations.

Additionally, there are a lot of missing values throughout all datasets, so they need to be addressed.

The contents of the `HOUR` column are stored as numeric, where infact it should be character as the hours represent categories.